// import './index.pug'
import $ from 'jquery'
// import 'owl.carousel2/dist/assets/owl.carousel.css'
// import 'owl.carousel2/dist/assets/owl.theme.default.css'
// import 'owl.carousel2'
import '@fancyapps/fancybox/dist/jquery.fancybox.css'
import 'slick-slider/slick/slick.css'
import 'slick-slider/slick/slick'
import 'jquery-form-styler/dist/jquery.formstyler.css'
// import 'jquery-form-styler/dist/jquery.formstyler.theme.css'
import 'jquery-form-styler/dist/jquery.formstyler'
import '@fancyapps/fancybox'
import './js/common'
import 'normalize.css'
import './sass/main.sass'

// import 'vue'
// import Bootstrap from 'bootstrap/dist/css/bootstrap.min.css'
// import Vue from 'vue'
// window.Vue = require('vue')
